spring:
  application:
    name: clientes

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}

  devtools:
    restart:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      access: read-only
  prometheus:    
    metrics:
      export:
        enabled: true
