spring:
  datasource:
    url: jdbc:h2:mem:clientesdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      # data-locations: classpath:data-dev.sql
